name: Manual Docker Image CI

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  REPO_NAME: nurdynzo
  IMAGE_NAME: test
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build, tag, and push image to GHCR
      id: build-image
      env:
        COMMIT_ID: ${{ github.sha }}
      run: |
        IMAGE_TAG=$(echo $COMMIT_ID | cut -c 1-7)
        docker build -t $REGISTRY/$REPO_NAME/$IMAGE_NAME:$IMAGE_TAG .
        docker push $REGISTRY/$REPO_NAME/$IMAGE_NAME:$IMAGE_TAG
        echo "image=$REGISTRY/$REPO_NAME/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT
    - name: SSH into EC2 Instance
      env:
          IMAGE: ${{ steps.build-image.outputs.image }}
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: IMAGE,TOKEN
          script: |
            echo "$TOKEN" | docker login ghcr.io -u USERNAME --password-stdin
            export EXTERNAL_VARIABLE="$IMAGE"
            docker-compose up -d
            docker ps     
